import Image from "next/image";
import styles from "@/styles/Home.module.css";
import NavBar from "@/Components/NavBar/NavBar";
import HeroSection from "@/Components/HeroSection/HeroSection";
import Tabs from "@/Components/Tabs/Tabs";
import Tab2 from "@/Components/Tab2/Tab2";
import Footer from "@/Components/Footer/Footer";
import Head from "next/head";

export default function Home() {
  return (
    <div className={styles.description}>
      <Head>
        <title>BasketFi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/basket.jpeg" />
      </Head>
      <NavBar />
      <HeroSection />
      <Tabs />
      <Tab2 className={styles.description_tab2} />
      <Footer />
    </div>
  );
}
